# Generated by Django 4.0.4 on 2022-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OldEra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_if',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
